Fix bug 250
openseattle/clearviction-next pull request #36
Opened 2023-03-16 19:27 UTC by e-papanicolas

This fixes [bug 250](https://airtable.com/appfJZShN8K4tcWHU/tblvBIYoi6TLmdRAv/viwArsFGvnIxdnKzK/reccExKCT4WLf2HM9?blocks=hide). Adds an updated url for one link, and corrects 2 other bad links.

2023-03-18 19:55 UTC, mhyneman8 commented
@e-papanicolas if you can fix the second link for work-study it still isn't working. 
Working link should be: https://studentaid.gov/understand-aid/types/work-study

2023-03-18 19:56 UTC, mhyneman8 requested changes
work study link needs to be updated

https://studentaid.gov/understand-aid/types/work-study

2023-03-19 01:23 UTC, e-papanicolas commented
I also updated the Pell grant link, which was not working. I couldn't determine the exact link that the original content was supposed to be using, so I will reach out to see if someone can verify if this link is a good replacement. In the meantime, this link does not lead to an error page.

2023-03-19 14:40 UTC, mhyneman8 approved these changes

2023-03-19 14:40 UTC, merged